name: 'CI'

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  unit_tests:
    name: 'Unit Tests'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: 'Check out code'
        uses: actions/checkout@v2
      - name: 'Restore dependencies'
        run: 'dotnet restore'
      - name: 'Run Unit Tests'
        run: 'dotnet test --no-restore --verbosity normal'